# Generated by Django 2.2.13 on 2020-06-26 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_name', models.CharField(max_length=64)),
                ('image', models.ImageField(upload_to='badges')),
                ('min_score', models.IntegerField(default=0)),
                ('max_score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('compitency', models.CharField(choices=[('Self Management', 'Self Management'), ('Self Awareness', 'Self Awareness'), ('Responsible Decision Making', 'Responsible Decision Making'), ('Social Awareness', 'Social Awareness'), ('Relationship Skills', 'Relationship Skills')], default='SELF MANAGEMENT', max_length=64)),
                ('theme', models.CharField(blank=True, max_length=64)),
                ('name', models.CharField(blank=True, max_length=128)),
                ('index', models.TextField(blank=True)),
                ('introduction', models.TextField(blank=True)),
                ('moral', models.TextField(blank=True)),
                ('num_pages', models.IntegerField(default=0)),
                ('date_uploaded', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.FileField(default='/logos/anonymous.jpg', upload_to='content_video')),
            ],
        ),
        migrations.CreateModel(
            name='Questions_Mapping',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('id_for_session', models.IntegerField(default=0)),
                ('serial_number', models.IntegerField(default=0)),
                ('question', models.CharField(default='', max_length=128)),
                ('option_A', models.CharField(default='', max_length=128)),
                ('option_B', models.CharField(default='', max_length=128)),
                ('option_C', models.CharField(default='', max_length=128)),
                ('option_D', models.CharField(blank=True, default='', max_length=128)),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=64)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Session')),
            ],
        ),
        migrations.CreateModel(
            name='Media_Content',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('id_for_session', models.IntegerField(default=0)),
                ('serial_number', models.IntegerField(default=0)),
                ('media_content', models.ImageField(blank=True, upload_to='content')),
                ('text_content', models.TextField(blank=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Session')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('feedback', models.TextField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Session')),
            ],
        ),
    ]
