# Generated by Django 2.2.13 on 2020-06-26 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='date_uploaded',
        ),
    ]
