# Generated by Django 2.2.13 on 2020-06-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions_mapping',
            name='option_a',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='questions_mapping',
            name='option_b',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='questions_mapping',
            name='option_c',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='questions_mapping',
            name='option_d',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
