# Generated by Django 2.2.13 on 2020-06-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200615_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions_mapping',
            name='option_a',
        ),
        migrations.RemoveField(
            model_name='questions_mapping',
            name='option_b',
        ),
        migrations.RemoveField(
            model_name='questions_mapping',
            name='option_c',
        ),
        migrations.RemoveField(
            model_name='questions_mapping',
            name='option_d',
        ),
        migrations.AddField(
            model_name='questions_mapping',
            name='correct_answer',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='questions_mapping',
            name='options',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=1),
        ),
    ]
