# Generated by Django 2.2.13 on 2020-06-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200615_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='content',
            new_name='text_content',
        ),
        migrations.AddField(
            model_name='session',
            name='image_content',
            field=models.ImageField(blank=True, upload_to='content'),
        ),
        migrations.AddField(
            model_name='session',
            name='video_content',
            field=models.FileField(blank=True, upload_to='content_video'),
        ),
    ]
