# Generated by Django 2.2.13 on 2020-06-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200618_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions_mapping',
            name='options',
        ),
        migrations.AddField(
            model_name='questions_mapping',
            name='option_A',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questions_mapping',
            name='option_B',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questions_mapping',
            name='option_C',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questions_mapping',
            name='option_D',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='questions_mapping',
            name='correct_answer',
            field=models.CharField(default='A', max_length=100),
        ),
        migrations.AlterField(
            model_name='questions_mapping',
            name='question',
            field=models.CharField(default='', max_length=100),
        ),
    ]
