# Generated by Django 2.2.13 on 2020-06-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200627_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media_content',
            name='media_content',
            field=models.ImageField(blank=True, null=True, upload_to='content'),
        ),
    ]
