# Generated by Django 2.2.13 on 2020-06-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_testclass_doc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testclass',
            name='name',
        ),
        migrations.AddField(
            model_name='testclass',
            name='doc',
            field=models.FileField(default='settings.MEDIA_ROOT/logos/anonymous.jpg', upload_to='content_video'),
        ),
    ]
