# Generated by Django 2.2.13 on 2020-06-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20200618_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creative_space',
            name='image',
            field=models.ImageField(blank=True, upload_to='creative_space'),
        ),
    ]
