# Generated by Django 2.2.13 on 2020-06-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20200624_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testclass',
            name='doc',
            field=models.FileField(default='/logos/anonymous.jpg', upload_to='content_video'),
        ),
    ]
