# Generated by Django 2.2.13 on 2020-06-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20200624_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testclass',
            name='doc',
        ),
        migrations.AddField(
            model_name='testclass',
            name='name',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
