# Generated by Django 2.2.13 on 2020-06-19 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20200618_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='session',
            name='image_content',
        ),
        migrations.RemoveField(
            model_name='session',
            name='text_content',
        ),
        migrations.RemoveField(
            model_name='session',
            name='video_content',
        ),
        migrations.CreateModel(
            name='Media_Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField(default=0)),
                ('media_content', models.FileField(blank=True, upload_to='content')),
                ('text_content', models.TextField(blank=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Session')),
            ],
        ),
    ]
