# Generated by Django 2.2.13 on 2020-06-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20200624_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testclass',
            name='name',
        ),
        migrations.AddField(
            model_name='testclass',
            name='doc',
            field=models.FileField(default='/logos/anonymous.jpg', upload_to='content_video'),
        ),
    ]
