# Generated by Django 2.2.13 on 2020-06-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20200624_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='compitency',
            field=models.CharField(choices=[('Self Management', 'Self Management'), ('Self Awareness', 'Self Awareness'), ('Responsible Decision Making', 'Responsible Decision Making'), ('Social Awareness', 'Social Awareness'), ('Relationship Skills', 'Relationship Skills')], default='SELF MANAGEMENT', max_length=64),
        ),
    ]
