# Generated by Django 2.2.13 on 2020-06-20 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_remove_feedback_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_id',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
    ]
