# Generated by Django 2.2.13 on 2020-06-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20200625_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='media_content',
            name='id_for_session',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questions_mapping',
            name='id_for_session',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questions_mapping',
            name='serial_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='session',
            name='num_pages',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='media_content',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='questions_mapping',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
