# Generated by Django 2.2.13 on 2020-06-20 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20200620_0437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
