# Generated by Django 2.2.13 on 2020-06-20 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20200620_0442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='learning_to',
        ),
    ]
