# Generated by Django 2.2.13 on 2020-06-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_remove_session_learning_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_name',
            field=models.CharField(choices=[('SELF MANAGEMENT', 'Self Management'), ('SELF AWARENESS', 'Self Awareness'), ('RESPONSIBLE DECISION MAKING', 'Responsible Decision Making'), ('SOCIAL AWARENESS', 'Social Awareness'), ('RELATIONSHIP SKILLS', 'Relationship Skills')], max_length=64),
        ),
        migrations.DeleteModel(
            name='Pillars',
        ),
    ]
