# Generated by Django 2.2.13 on 2020-06-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20200620_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creative_space',
            name='session',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='result_session',
            name='session',
        ),
        migrations.RemoveField(
            model_name='result_session',
            name='user',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='session_name',
            new_name='compitency',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='achievements_today',
            new_name='index',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='check_in_content',
            new_name='introduction',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='close_content',
            new_name='moral',
        ),
        migrations.RemoveField(
            model_name='questions_mapping',
            name='question_number',
        ),
        migrations.RemoveField(
            model_name='session',
            name='how_am_i_learning',
        ),
        migrations.RemoveField(
            model_name='session',
            name='introduce_to_session',
        ),
        migrations.RemoveField(
            model_name='session',
            name='quality_focused',
        ),
        migrations.RemoveField(
            model_name='session',
            name='session_id',
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='session',
            name='name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='session',
            name='theme',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='badge',
            name='badge_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='media_content',
            name='media_content',
            field=models.ImageField(blank=True, upload_to='content'),
        ),
        migrations.AlterField(
            model_name='questions_mapping',
            name='correct_answer',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=64),
        ),
        migrations.AlterField(
            model_name='questions_mapping',
            name='option_A',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='questions_mapping',
            name='option_B',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='questions_mapping',
            name='option_C',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='questions_mapping',
            name='option_D',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='questions_mapping',
            name='question',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.DeleteModel(
            name='Badge_Allot',
        ),
        migrations.DeleteModel(
            name='Creative_Space',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Result_Session',
        ),
    ]
